config/routes.rb
Rails.application.routes.draw do
  resources :manager_associations
  resources :input_streams
  resources :users do
    member do
      get 'posture'
    end
  end
  resources :sessions

  get 'login' => 'sessions#new', as: :home
  get 'dashboard/index' => 'dashboard#index', as: :dashboard
  get 'history/index' => 'history#index', as: :history
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get '/inputstreamround/:m1/:m2/:m3/:m4', to: 'input_streams#insertRound'

  root to: 'sessions#new'
  

end

app/models/manager_association.rb
class ManagerAssociation < ActiveRecord::Base
  #Associations
  belongs_to :manager, class_name: :user
  belongs_to :employee, class_name: :user
  
  #Validations
  validates :employee_id, presence: true, numericality: { only_integer: true }
  validates :manager_id, presence: true, numericality: { only_integer: true }
  validate :validate_employee_id, :validate_manager_id

  #Scopes
  scope :active, -> {where("active = ?", true)}
  
private

  def validate_employee_id
    errors.add(:employee_id, "is not an employee in our system") unless User.exists?(self.manager_id)
  end

  def validate_manager_id
    errors.add(:manager_id, "is not an employee in our system") unless User.exists?(self.employee_id)
  end
end

app/controllers/manager_associations_controller.rb
class ManagerAssociationsController < ApplicationController
  before_action :set_manager_association, only: [:show, :edit, :update, :destroy]

  # GET /manager_associations
  # GET /manager_associations.json
  def index
    @manager_associations = ManagerAssociation.all
  end

  # GET /manager_associations/1
  # GET /manager_associations/1.json
  def show
  end

  # GET /manager_associations/new
  def new
    @manager_association = ManagerAssociation.new
  end

  # GET /manager_associations/1/edit
  def edit
  end

  # POST /manager_associations
  # POST /manager_associations.json
  def create
    @manager_association = ManagerAssociation.new(manager_association_params)

    respond_to do |format|
      if @manager_association.save
        format.html { redirect_to @manager_association, notice: 'Manager association was successfully created.' }
        format.json { render :show, status: :created, location: @manager_association }
      else
        format.html { render :new }
        format.json { render json: @manager_association.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manager_associations/1
  # PATCH/PUT /manager_associations/1.json
  def update
    respond_to do |format|
      if @manager_association.update(manager_association_params)
        format.html { redirect_to @manager_association, notice: 'Manager association was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager_association }
      else
        format.html { render :edit }
        format.json { render json: @manager_association.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manager_associations/1
  # DELETE /manager_associations/1.json
  def destroy
    @manager_association.destroy
    respond_to do |format|
      format.html { redirect_to manager_associations_url, notice: 'Manager association was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager_association
      @manager_association = ManagerAssociation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_association_params
      params.require(:manager_association).permit(:manager_id, :employee_id, :active, :boolean)
    end
end

app/helpers/manager_associations_helper.rb
module ManagerAssociationsHelper
end

app/views/manager_associations/_form.html.erb
<%= form_for(@manager_association) do |f| %>
  <% if @manager_association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager_association.errors.count, "error") %> prohibited this manager_association from being saved:</h2>

      <ul>
      <% @manager_association.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manager_id %><br>
    <%= f.number_field :manager_id %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.text_field :active %>
  </div>
  <div class="field">
    <%= f.label :boolean %><br>
    <%= f.text_field :boolean %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manager_associations/edit.html.erb
<h1>Editing Manager Association</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager_association %> |
<%= link_to 'Back', manager_associations_path %>

app/views/manager_associations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manager Associations</h1>

<table>
  <thead>
    <tr>
      <th>Manager</th>
      <th>Employee</th>
      <th>Active</th>
      <th>Boolean</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manager_associations.each do |manager_association| %>
      <tr>
        <td><%= manager_association.manager_id %></td>
        <td><%= manager_association.employee_id %></td>
        <td><%= manager_association.active %></td>
        <td><%= manager_association.boolean %></td>
        <td><%= link_to 'Show', manager_association %></td>
        <td><%= link_to 'Edit', edit_manager_association_path(manager_association) %></td>
        <td><%= link_to 'Destroy', manager_association, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager association', new_manager_association_path %>

app/views/manager_associations/new.html.erb
<h1>New Manager Association</h1>

<%= render 'form' %>

<%= link_to 'Back', manager_associations_path %>

app/views/manager_associations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manager:</strong>
  <%= @manager_association.manager_id %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @manager_association.employee_id %>
</p>

<p>
  <strong>Active:</strong>
  <%= @manager_association.active %>
</p>

<p>
  <strong>Boolean:</strong>
  <%= @manager_association.boolean %>
</p>

<%= link_to 'Edit', edit_manager_association_path(@manager_association) %> |
<%= link_to 'Back', manager_associations_path %>