config/routes.rb
Rails.application.routes.draw do
  resources :manager_associations
  resources :input_streams
  resources :users do
    member do
      get 'posture'
    end
  end
  resources :sessions

  get 'login' => 'sessions#new', as: :home
  get 'dashboard/index' => 'dashboard#index', as: :dashboard
  get 'history/index' => 'history#index', as: :history
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get '/inputstreamround/:m1/:m2/:m3/:m4', to: 'input_streams#insertRound'

  root to: 'sessions#new'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postchair</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %> <%= action_name %>">
<nav class="blue lighten-1">
  <div class="nav-wrapper container">
    <% if logged_in? %>
     <%= link_to 'Postchair', dashboard_path, class: "brand-logo"%>
    <% else %>
      <%= link_to 'Postchair', home_path, class: "brand-logo"%>
    <% end %>
    <ul id="nav-mobile" class="right">

        <% if logged_in? %>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
         <li><%= link_to 'History', history_path %></li>
         <% end %>
	  	  <!-- <div id="login"> -->
          <!-- content once logged in goes here -->
          <% if logged_in? %>
            <li><%= link_to 'Logout', logout_path %></li>
          <% else %>
            <li><%= link_to 'Login', login_path %></li>
         <% end %>
        </ul>

    <!-- navigation options go here -->

  </div>
</nav>


<%= yield %>

</body>
</html>